language: node_js
node_js:
  - "12"
env:
  - NODE_ENV=production
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
    - npm test